apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: template-open-project
  annotations:
    github.com/project-slug: incaya/template-open-project
    backstage.io/techdocs-ref: dir:./project-documentation
spec:
  type: template
  lifecycle: open-source
  owner: user:default/alexisjanvier
