post_bump_hooks = [
  """
    sh -c 'cp CHANGELOG.md ./project-documentation/changelog/current.md'
  """,
  "git add ./project-documentation/changelog/current.md",
  "cog commit chore bump release",
  """
    sh -c "git push origin {{version}}"
  """,
  """
    sh -c "git push"
  """,
]
pre_bump_hooks = []

[commit_types]

[changelog]
authors = [
  {signature = "Alexis Janvier", username = "alexisjanvier"},
  {signature = "Thomas Berriot", username = "tberriot"},
  {signature = "Thomas Maziere", username = "tmaziere"},
]
owner = "incaya"
path = "CHANGELOG.md"
remote = "github.com"
repository = "projet-incaya"
template = "remote"

[bump_profiles]
